name: foreal_property
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.5.4


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.3
  flutter_riverpod: ^2.6.1
  flutter_sticky_header: ^0.7.0
  easy_stepper: ^0.8.5+1
 
  auto_size_text: ^3.0.0
  image_picker: ^1.1.2
  timeline_tile: ^2.0.0
  extended_image: ^9.1.0
  rename_app: ^1.6.2
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  freezed: ^2.5.7
  riverpod_generator: ^2.6.3
  riverpod_annotation: ^2.6.1
  loading_animation_widget: ^1.3.0
  dio: ^5.8.0+1
  shared_preferences: ^2.5.1
  google_places_flutter: ^2.1.0
  intl: ^0.19.0
  pdfx: ^2.9.1
  file_picker: ^10.1.9
  minio: ^3.5.7
  cached_network_image: ^3.4.1
  url_launcher: ^6.3.1
#  flutter_reorderable_grid_view: ^5.5.0
#  flutter_keyboard_visibility: ^6.0.0
  dropdown_button2: ^2.3.9
  bottom_picker: ^3.2.1
  google_maps_flutter: ^2.12.3
  syncfusion_flutter_datepicker: ^30.1.40
  flutter_hooks: ^0.21.2
  hooks_riverpod: ^2.6.1
  flutter_slidable: ^4.0.1
  animated_reorderable_list: ^1.3.0
  expansion_tile_list: ^2.0.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  json_serializable: ^6.9.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/pdfs/file.pdf
  #   - images/a_dot_ham.jpeg




  fonts:
    - family: Plus Jakarta Sans
      fonts:
        - asset: assets/fonts/PlusJakartaSans-VariableFont.ttf
 
 