// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'contact_list_model.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

ContactList _$ContactListFromJson(Map<String, dynamic> json) => ContactList(
      contactId: (json['contactId'] as num?)?.toInt(),
      contactUniqueId: json['contactUniqueId'] as String?,
      contactDisplayId: json['contactDisplayId'],
      companyName: json['companyName'],
      isInvestor: json['isInvestor'] as bool?,
      isDeveloper: json['isDeveloper'] as bool?,
      isAgent: json['isAgent'],
      isFirstHomeBuyer: json['isFirstHomeBuyer'] as bool?,
      type: json['type'] as String?,
      typeIam: json['typeIAM'],
      mobileNumber: json['mobileNumber'] as String?,
      priceRange: json['priceRange'],
      postcode: json['postcode'],
      regions: json['regions'],
      shareStatus: (json['shareStatus'] as num?)?.toInt(),
      loggedAgent: json['loggedAgent'],
      agent: (json['agent'] as num?)?.toInt(),
      canUpdateShareStatus: json['canUpdateShareStatus'] as bool?,
      userId: (json['userId'] as num?)?.toInt(),
      firstName: json['firstName'] as String?,
      lastName: json['lastName'] as String?,
      email: json['email'] as String?,
      userType: (json['userType'] as num?)?.toInt(),
      userRoles: json['userRoles'],
      userRoleId: (json['userRoleID'] as num?)?.toInt(),
      subscriptionId: (json['subscriptionId'] as num?)?.toInt(),
      subscriptionName: json['subscriptionName'],
      agencyUniqueId: json['agencyUniqueID'],
      addedByAgencyId: json['addedByAgencyID'],
      address: json['address'],
      contact: json['contact'],
      agencyId: (json['agencyID'] as num?)?.toInt(),
      isSecondry: json['isSecondry'] as bool?,
      isBranch: json['isBranch'] as bool?,
      hasSolicitorDetails: json['hasSolicitorDetails'] as bool?,
      agentUniqueId: json['agentUniqueId'],
      agentId: (json['agentId'] as num?)?.toInt(),
      affiliateUniqueId: json['affiliateUniqueId'],
      affiliateId: json['affiliateId'],
      phone: json['phone'] as String?,
      staffId: (json['staffId'] as num?)?.toInt(),
      agencyStaffUniqueId: json['agencyStaffUniqueId'],
      isStaff: json['isStaff'] as bool?,
      agentMgt: json['agentMgt'],
      taskCalendarMgt: json['taskCalendarMgt'],
      contactMgt: json['contactMgt'],
      propertyMgt: json['propertyMgt'],
      agreementDocsMgt: json['agreementDocsMgt'],
      packagesPricingstructure: json['packagesPricingstructure'],
      subscriptionBilling: json['subscriptionBilling'],
      paymentsReconcillation: json['paymentsReconcillation'],
      dashboard: json['dashboard'],
      support: json['support'],
      newsletter: json['newsletter'],
      hasMultipleProfiles: json['hasMultipleProfiles'] as bool?,
      tenantId: (json['tenantId'] as num?)?.toInt(),
      tenantFolioId: (json['tenantFolioId'] as num?)?.toInt(),
      folioUniqueId: json['folioUniqueId'],
      propertyId: (json['propertyId'] as num?)?.toInt(),
      supplierId: (json['supplierId'] as num?)?.toInt(),
      supplierUniqueId: json['supplierUniqueId'],
      userProfiles: json['userProfiles'],
    );
