// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'get_property_list_model.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

GetPropertyList _$GetPropertyListFromJson(Map<String, dynamic> json) =>
    GetPropertyList(
      propertyId: (json['propertyId'] as num?)?.toInt(),
      propertyUniqueId: json['propertyUniqueID'] as String?,
      agencyId: (json['agencyId'] as num?)?.toInt(),
      agentId: (json['agentId'] as num?)?.toInt(),
      agentUniqueId: json['agentUniqueId'],
      agentName: json['agentName'] as String?,
      agentProfilePic: json['agentProfilePic'] as String?,
      agentContact: json['agentContact'] as String?,
      agentEmail: json['agentEmail'] as String?,
      propertyContactId: json['propertyContactId'],
      propertyName: json['propertyName'],
      agencyUniqueId: json['agencyUniqueId'],
      agencyName: json['agencyName'] as String?,
      agencyLogo: json['agencyLogo'] as String?,
      agencyBrandColor: json['agencyBrandColor'] as String?,
      postCode: json['postCode'] as String?,
      primaryContactUniqueId: json['primaryContactUniqueID'] as String?,
      propertyPic: json['propertyPic'] as String?,
      primaryContactName: json['primaryContactName'],
      getFormatedAddress: json['getFormatedAddress'] as String?,
      propertyGooglePlacesLocation:
          json['propertyGooglePlacesLocation'] as String?,
      propertyGooglePlacesLocationLat: json['propertyGooglePlacesLocationLat'],
      propertyGooglePlacesLocationLong:
          json['propertyGooglePlacesLocationLong'],
      propertySaleRental: json['propertySaleRental'],
      propertyDescription: json['propertyDescription'],
      propertyReferenceField: json['propertyReferenceField'],
      countBedrooms: (json['countBedrooms'] as num?)?.toInt(),
      countBathrooms: (json['countBathrooms'] as num?)?.toInt(),
      countRooms: json['countRooms'],
      countCarParking: (json['countCarParking'] as num?)?.toInt(),
      countServantQuarters: json['countServantQuarters'],
      countAttic: json['countAttic'],
      countAnnexes: json['countAnnexes'],
      countKitchen: json['countKitchen'],
      countDrawingRooms: json['countDrawingRooms'],
      countStorageRooms: json['countStorageRooms'],
      propertySellerConvyencorId: json['propertySellerConvyencorId'],
      propertyBuyerConvyencorId: json['propertyBuyerConvyencorId'],
      propertyType: json['propertyType'] as String?,
      propertyBuildingTypeLotplan: json['propertyBuildingTypeLotplan'],
      propertyBuildingTypeYearBuilt: json['propertyBuildingTypeYearBuilt'],
      propertyBuildingTypeZoning: json['propertyBuildingTypeZoning'],
      propertySoldDate: json['propertySoldDate'],
      propertySoldPrice: json['propertySoldPrice'],
      propertyPrice: json['propertyPrice'],
      createdDate: json['createdDate'] == null
          ? null
          : DateTime.parse(json['createdDate'] as String),
      isDeleted: json['isDeleted'],
      deletedOn: json['deletedOn'],
      isApproved: json['isApproved'],
      approvedOn: json['approvedOn'],
      isPropertyEnlist: json['isPropertyEnlist'],
      propertyEnlistDate: json['propertyEnlistDate'],
      isAgent: json['isAgent'],
      isWishlist: json['isWishlist'] as bool?,
      isPropertyScrap: json['isPropertyScrap'],
      sPropertyType: json['sPropertyType'] as String?,
      purpose: (json['purpose'] as num?)?.toInt(),
      showText: json['showText'],
      isRemoveFromList: json['isRemoveFromList'],
      leasedSoldProperty: json['leasedSoldProperty'] as bool?,
      isPropertyLost: json['isPropertyLost'] as bool?,
      shareStatus: (json['shareStatus'] as num?)?.toInt(),
      listingStatus: json['listingStatus'],
      sharedAgents: json['sharedAgents'],
      propertyPics: json['propertyPics'] as List<dynamic>?,
      additionalFeatures: json['additionalFeatures'],
      createdBy: json['createdBy'] as String?,
      sPropertyStatus: json['sPropertyStatus'] as String?,
      propertyStatusColor: json['propertyStatusColor'] as String?,
      propertyHeading: json['propertyHeading'],
      propertyLandAreaL: json['propertyLandAreaL'],
      propertyLandAreaW: json['propertyLandAreaW'],
      state: json['state'] as String?,
      suburb: json['suburb'] as String?,
      streetName: json['streetName'] as String?,
      unitNumber: json['unitNumber'] as String?,
      streetNumber: json['streetNumber'] as String?,
    );
