// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'tenant_contact_model.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

TenantContactModel _$TenantContactModelFromJson(Map<String, dynamic> json) =>
    TenantContactModel(
      userId: (json['userId'] as num?)?.toInt(),
      supplierId: json['supplierId'],
      firstName: json['firstName'] as String?,
      photoByte: json['photoByte'],
      photoPath: json['photo_Path'],
      bankReference: json['bankReference'],
      profileCropedImg: json['profile_Croped_Img'],
      lastName: json['lastName'] as String?,
      email: json['email'] as String?,
      userType: (json['userType'] as num?)?.toInt(),
      userRoleId: (json['userRoleID'] as num?)?.toInt(),
      subscriptionId: (json['subscriptionId'] as num?)?.toInt(),
      agencyUniqueId: json['agencyUniqueID'],
      address: json['address'] as String?,
      addressPostCode: json['addressPostCode'],
      addressState: json['addressState'],
      viewType: (json['viewType'] as num?)?.toInt(),
      contact: json['contact'],
      agencyId: json['agencyID'],
      agentUniqueId: json['agentUniqueId'],
      agentId: (json['agentId'] as num?)?.toInt(),
      webRootPath: json['webRootPath'],
      agentList: json['agentList'],
      contactId: (json['contactId'] as num?)?.toInt(),
      contactUniqueId: json['contactUniqueId'] as String?,
      contactDisplayId: json['contactDisplayId'],
      titleValues: json['titleValues'],
      birthday: json['birthday'],
      title: json['title'],
      contactStatusId: json['contactStatusId'],
      typeIam: json['typeIAM'],
      otherDetailsType: json['otherDetailsType'],
      priceRange: json['priceRange'],
      anniversary: json['anniversary'],
      remarks: json['remarks'],
      notes: json['notes'],
      isExternal: json['isExternal'],
      contactStatusValues: json['contactStatusValues'],
      ddlOtherDetailsType: json['ddlOtherDetailsType'],
      createdDate: json['createdDate'] == null
          ? null
          : DateTime.parse(json['createdDate'] as String),
      mobileNumber: json['mobileNumber'] as String?,
      landlineNumber: json['landlineNumber'],
      landlineNumber1: json['landlineNumber1'],
      companyAddress: json['companyAddress'],
      companyName: json['companyName'],
      propertyAddress: json['propertyAddress'],
      abn: json['abn'],
      acn: json['acn'],
      isMarried: json['isMarried'] as bool?,
      maritalStatus: (json['maritalStatus'] as num?)?.toInt(),
      spouseName: json['spouseName'],
      spouseMobileNumber: json['spouseMobileNumber'],
      spouseAddress: json['spouseAddress'],
      spouseEmail: json['spouseEmail'],
      isInvestor: json['isInvestor'] as bool?,
      isDeveloper: json['isDeveloper'] as bool?,
      isFirstHomeBuyer: json['isFirstHomeBuyer'] as bool?,
      isSelling: json['isSelling'] as bool?,
      isRenting: json['isRenting'] as bool?,
      isBuying: json['isBuying'] as bool?,
      isSupplier: json['isSupplier'] as bool?,
      priceRangeValues: json['priceRangeValues'],
      ddlMaritalStatus: json['ddlMaritalStatus'],
      postcode: json['postcode'],
      regions: json['regions'],
      facebookUrl: json['facebookUrl'],
      linkedinUrl: json['linkedinUrl'],
      twitterUrl: json['twitterUrl'],
      instagramUrl: json['instagramUrl'],
      isDeleted: json['isDeleted'] as bool?,
      communicationType: json['communicationType'],
      isNotice: json['isNotice'] as bool?,
      isEmail: json['isEmail'] as bool?,
      isPhone: json['isPhone'] as bool?,
      loggedUserName: json['loggedUserName'],
      communicationTypeList: json['communicationTypeList'],
      idType: json['idType'],
      idTypeList: json['idTypeList'],
      idNumber: json['idNumber'],
      bDocumentImage: json['bDocumentImage'],
      pDocumentImagePath: json['pDocumentImagePath'],
      isAddedByAffiliate: json['isAddedByAffiliate'] as bool?,
      affiliateId: json['affiliateId'],
      contactType: json['contactType'],
      contactCategory: (json['contactCategory'] as num?)?.toInt(),
      contactTypeList: json['contactTypeList'],
      enquiryListingModel: json['enquiryListingModel'],
      sellerEnquiryListingModel: json['sellerEnquiryListingModel'],
      offerListingModel: json['offerListingModel'],
      buyerOfferListingModel: json['buyerOfferListingModel'],
      contactNotes: json['contactNotes'] as List<dynamic>?,
      contactChanges: json['contactChanges'],
      isAgentLogged: json['isAgentLogged'] as bool?,
      isAffiliateLogged: json['isAffiliateLogged'] as bool?,
      loggedUserId: (json['loggedUserId'] as num?)?.toInt(),
      followupDate: json['followupDate'],
      note: json['note'],
      isPrimary: json['isPrimary'],
      relatedProperties: json['relatedProperties'] as List<dynamic>?,
      tenantFolioDetails: json['tenantFolioDetails'] as List<dynamic>?,
      supplierDetails: json['supplierDetails'],
      supplierPaymentMethod: json['supplierPaymentMethod'],
      propertyOwnerFolioDetails:
          json['propertyOwnerFolioDetails'] as List<dynamic>?,
      updateSupplierPaymentMethod: json['updateSupplierPaymentMethod'] as bool?,
      image: json['image'],
      contactReference: json['contactReference'],
      postCodeName: json['postCodeName'],
      solicitorFirmName: json['solicitorFirmName'],
      solicitorPrincipalName: json['solicitorPrincipalName'],
      solicitorAddress: json['solicitorAddress'],
      solicitorEmail: json['solicitorEmail'],
      solicitorPhone: json['solicitorPhone'],
      solicitorFax: json['solicitorFax'],
      propertyUniqueId: json['propertyUniqueId'],
    );

SearchContactModel _$SearchContactModelFromJson(Map<String, dynamic> json) =>
    SearchContactModel(
      id: (json['id'] as num?)?.toInt(),
      uid: json['uid'] as String?,
      name: json['name'] as String?,
      agentId: (json['agentId'] as num?)?.toInt(),
      email: json['email'] as String?,
    );
