// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'user_model.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_$UserModelImpl _$$UserModelImplFromJson(Map<String, dynamic> json) =>
    _$UserModelImpl(
      userUniqueId: json['userUniqueId'] as String?,
      profilePicture: json['profilePicture'],
      userName: json['userName'],
      userEmail: json['userEmail'],
      isActive: json['isActive'],
      image: json['image'],
      imageLink: json['imageLink'],
      imageName: json['imageName'],
      lastUpdated: json['lastUpdated'],
      isAuthenticated: json['isAuthenticated'] as bool?,
      isSoleProp: json['isSoleProp'] as bool?,
      facebookId: json['facebookId'],
      eAuthenticationType: (json['eAuthenticationType'] as num?)?.toInt(),
      token: json['token'] as String?,
      abn: json['abn'],
      isNewUser: json['isNewUser'],
      hideTask: json['hideTask'],
      hideCalendar: json['hideCalendar'],
      hideBranches: json['hideBranches'],
      hideAnalytics: json['hideAnalytics'],
      disableeSignature: json['disableeSignature'],
      currentProfile: json['currentProfile'],
      userId: (json['userId'] as num?)?.toInt(),
      firstName: json['firstName'] as String?,
      lastName: json['lastName'] as String?,
      email: json['email'] as String?,
      userType: (json['userType'] as num?)?.toInt(),
      userRoles: (json['userRoles'] as List<dynamic>?)
          ?.map((e) => (e as num).toInt())
          .toList(),
      userRoleId: (json['userRoleId'] as num?)?.toInt(),
      subscriptionId: (json['subscriptionId'] as num?)?.toInt(),
      subscriptionName: json['subscriptionName'],
      agencyUniqueId: json['agencyUniqueId'],
      addedByAgencyId: json['addedByAgencyId'],
      address: json['address'],
      contact: json['contact'],
      agencyId: json['agencyId'],
      isSecondry: json['isSecondry'] as bool?,
      isBranch: json['isBranch'] as bool?,
      hasSolicitorDetails: json['hasSolicitorDetails'] as bool?,
      agentUniqueId: json['agentUniqueId'],
      agentId: json['agentId'],
      affiliateUniqueId: json['affiliateUniqueId'],
      affiliateId: json['affiliateId'],
      contactId: (json['contactId'] as num?)?.toInt(),
      contactUniqueId: json['contactUniqueId'] as String?,
      phone: json['phone'],
      staffId: (json['staffId'] as num?)?.toInt(),
      agencyStaffUniqueId: json['agencyStaffUniqueId'],
      isStaff: json['isStaff'] as bool?,
      agentMgt: json['agentMgt'],
      taskCalendarMgt: json['taskCalendarMgt'],
      contactMgt: json['contactMgt'],
      propertyMgt: json['propertyMgt'],
      agreementDocsMgt: json['agreementDocsMgt'],
      packagesPricingstructure: json['packagesPricingstructure'],
      subscriptionBilling: json['subscriptionBilling'],
      paymentsReconcillation: json['paymentsReconcillation'],
      dashboard: json['dashboard'],
      support: json['support'],
      newsletter: json['newsletter'],
      hasMultipleProfiles: json['hasMultipleProfiles'] as bool?,
      tenantId: (json['tenantId'] as num?)?.toInt(),
      tenantFolioId: (json['tenantFolioId'] as num?)?.toInt(),
      folioUniqueId: json['folioUniqueId'],
      propertyId: (json['propertyId'] as num?)?.toInt(),
      supplierId: (json['supplierId'] as num?)?.toInt(),
      supplierUniqueId: json['supplierUniqueId'],
      userProfiles: (json['userProfiles'] as List<dynamic>?)
          ?.map((e) => UserProfile.fromJson(e as Map<String, dynamic>))
          .toList(),
    );

Map<String, dynamic> _$$UserModelImplToJson(_$UserModelImpl instance) =>
    <String, dynamic>{
      'userUniqueId': instance.userUniqueId,
      'profilePicture': instance.profilePicture,
      'userName': instance.userName,
      'userEmail': instance.userEmail,
      'isActive': instance.isActive,
      'image': instance.image,
      'imageLink': instance.imageLink,
      'imageName': instance.imageName,
      'lastUpdated': instance.lastUpdated,
      'isAuthenticated': instance.isAuthenticated,
      'isSoleProp': instance.isSoleProp,
      'facebookId': instance.facebookId,
      'eAuthenticationType': instance.eAuthenticationType,
      'token': instance.token,
      'abn': instance.abn,
      'isNewUser': instance.isNewUser,
      'hideTask': instance.hideTask,
      'hideCalendar': instance.hideCalendar,
      'hideBranches': instance.hideBranches,
      'hideAnalytics': instance.hideAnalytics,
      'disableeSignature': instance.disableeSignature,
      'currentProfile': instance.currentProfile,
      'userId': instance.userId,
      'firstName': instance.firstName,
      'lastName': instance.lastName,
      'email': instance.email,
      'userType': instance.userType,
      'userRoles': instance.userRoles,
      'userRoleId': instance.userRoleId,
      'subscriptionId': instance.subscriptionId,
      'subscriptionName': instance.subscriptionName,
      'agencyUniqueId': instance.agencyUniqueId,
      'addedByAgencyId': instance.addedByAgencyId,
      'address': instance.address,
      'contact': instance.contact,
      'agencyId': instance.agencyId,
      'isSecondry': instance.isSecondry,
      'isBranch': instance.isBranch,
      'hasSolicitorDetails': instance.hasSolicitorDetails,
      'agentUniqueId': instance.agentUniqueId,
      'agentId': instance.agentId,
      'affiliateUniqueId': instance.affiliateUniqueId,
      'affiliateId': instance.affiliateId,
      'contactId': instance.contactId,
      'contactUniqueId': instance.contactUniqueId,
      'phone': instance.phone,
      'staffId': instance.staffId,
      'agencyStaffUniqueId': instance.agencyStaffUniqueId,
      'isStaff': instance.isStaff,
      'agentMgt': instance.agentMgt,
      'taskCalendarMgt': instance.taskCalendarMgt,
      'contactMgt': instance.contactMgt,
      'propertyMgt': instance.propertyMgt,
      'agreementDocsMgt': instance.agreementDocsMgt,
      'packagesPricingstructure': instance.packagesPricingstructure,
      'subscriptionBilling': instance.subscriptionBilling,
      'paymentsReconcillation': instance.paymentsReconcillation,
      'dashboard': instance.dashboard,
      'support': instance.support,
      'newsletter': instance.newsletter,
      'hasMultipleProfiles': instance.hasMultipleProfiles,
      'tenantId': instance.tenantId,
      'tenantFolioId': instance.tenantFolioId,
      'folioUniqueId': instance.folioUniqueId,
      'propertyId': instance.propertyId,
      'supplierId': instance.supplierId,
      'supplierUniqueId': instance.supplierUniqueId,
      'userProfiles': instance.userProfiles,
    };

_$UserProfileImpl _$$UserProfileImplFromJson(Map<String, dynamic> json) =>
    _$UserProfileImpl(
      userId: (json['userId'] as num?)?.toInt(),
      createdAt: json['createdAt'] == null
          ? null
          : DateTime.parse(json['createdAt'] as String),
      userRoleId: (json['userRoleId'] as num?)?.toInt(),
      userRoleLabel: json['userRoleLabel'] as String?,
      isActive: json['isActive'] as bool?,
    );

Map<String, dynamic> _$$UserProfileImplToJson(_$UserProfileImpl instance) =>
    <String, dynamic>{
      'userId': instance.userId,
      'createdAt': instance.createdAt?.toIso8601String(),
      'userRoleId': instance.userRoleId,
      'userRoleLabel': instance.userRoleLabel,
      'isActive': instance.isActive,
    };
